language: groovy

before_install:
  - sudo add-apt-repository ppa:linuxuprising/java -y
  - sudo apt update -q
  - sudo apt install oracle-java10-installer oracle-java10-set-default -y

jobs:
  include:
    - stage: run class tests
      script: ./mvnw test
    - stage: run service tests
      script: ./mvnw verify